# Copyright (c) 2023, Bennett Samowich <bennett@foolean.org>
# All rights reserved
# SPDX short identifier: BSD-3-Clause
---

# We put the entire role in a block so we can create
# a role specific tag, which saves the caller from
# having to do so in their playbook.
- name: Role foolean/selinux
  block:

    - name: Ensure selinux is installed (CIS)
      become: true
      ansible.builtin.package:
        name: 'libselinux'
        state: present
      when:
        - ansible_os_family == 'RedHat'

    - name: Ensure setroubleshoot is not installed (CIS)
      become: true
      ansible.builtin.package:
        name: 'setroubleshoot'
        state: absent
      when:
        - ansible_os_family == 'RedHat'

    - name: Ensure MCS Translation service (mcstrans) is not installed (CIS)
      become: true
      ansible.builtin.package:
        name: 'mcstrans'
        state: absent
      when:
        - ansible_os_family == 'RedHat'

    - name: Ensure selinux policy utils are installed
      become: true
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      with_items:
        - 'policycoreutils'
        - 'policycoreutils-python-utils'
        - 'checkpolicy'
      when:
        - ansible_os_family == 'RedHat'

    - name: Set selinux policy and state (CIS)
      become: true
      ansible.posix.selinux:
        policy: "{{ selinux_policy }}"
        state: "{{ selinux_state }}"
      when:
        - selinux_state != "disabled"
        - ansible_os_family == 'RedHat'

    - name: Disable selinux
      become: true
      ansible.posix.selinux:
        state: "{{ selinux_state }}"
      when:
        - selinux_state == "disabled"
        - ansible_os_family == 'RedHat'

    - name: CIS | Ensure SELinux is not disabled in bootloader configuration (check selinux)
      become: true
      ansible.builtin.command:
        cmd: "grep -P 'GRUB_CMDLINE_LINUX=.* (selinux=0)' /etc/default/grub"
      check_mode: false
      changed_when: selinux_kernel_args.rc == 0
      failed_when: selinux_kernel_args.rc == -1
      register: selinux_kernel_args

    - name: CIS | Ensure SELinux is not disabled in bootloader configuration (remove selinux)
      become: true
      ansible.builtin.command:
        cmd: "grubby --update-kernel ALL --remove-args 'selinux=0'"
      when:
        - selinux_kernel_args.rc == 0

    - name: CIS | Ensure SELinux is not disabled in bootloader configuration (check enforcing)
      become: true
      ansible.builtin.command:
        cmd: "grep -P 'GRUB_CMDLINE_LINUX=.* (enforcing=0)' /etc/default/grub"
      check_mode: false
      changed_when: selinux_kernel_args.rc == 0
      failed_when: selinux_kernel_args.rc == -1
      register: selinux_kernel_args

    - name: CIS | Ensure SELinux is not disabled in bootloader configuration (remove enforcing)
      become: true
      ansible.builtin.command:
        cmd: "grubby --update-kernel ALL --remove-args 'enforcing=0'"
      when:
        - selinux_kernel_args.rc == 0

  # Tags to be applied to this role (block)
  tags:
    - 'role_foolean_selinux'
